### ISSUE TITLE
Support Phantomjs 2.0

### ISSUE THREAD

**Issue by Stofkn** [peerigon/phridge#30]
Hi!

Is there any support for Phantomjs 2.0 upcoming?

Kind regards
Kristof

**Comment by jhnns** [comment]
The node wrapper for PhantomJS is still deferring the release because of issues with the binaries on Linux and OSX (Medium/phantomjs#288).

Given from [the changelog](https://github.com/ariya/phantomjs/blob/0352ddb502be9cb53cdb173fd7d97e3764e0c222/ChangeLog) there has not been a breaking change. I've installed the binaries via homebrew and tested phridge against PhantomJS 2.0 and everything was working fine (though I had to adjust a test because an error message has changed).

I've even experienced a *huge* performance increase of about 400-500% (at least on OSX).

**Comment by soda-wy** [comment]
expect 2.0！

**Comment by alexpts** [comment]
+1

**Comment by platypusMaximus** [comment]
+1

**Comment by nathanjohnson320** [comment]
:+1:

**Comment by interactionist** [comment]
+1

@jhnns Can you explain how to use the phantomJS 2.0 binary instead of the bundled one? Thanks.

**Comment by jhnns** [comment]
### 1. Install phantomjs 2.0 (via homebrew)
`brew install phantomjs`

### 2. Replace binary inside phridge
`rm -rf node_modules/phridge/node_modules/phantomjs/lib/phantom/bin/phantomjs`
`ln /usr/local/bin/phantomjs node_modules/phridge/node_modules/phantomjs/lib/phantom/bin/phantomjs`

**Comment by JonnyBGod** [comment]
PhantomJs 2.1 was release a few days ago. Can we update this now?

**Comment by jhnns** [comment]
phridge `2.0.0` with PhantomJS `2.1.3` shipped today
